// Mocks generated by Mockito 5.4.4 from annotations
// in checklist_app/test/features/auth/auth_controller_profile_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:checklist_app/features/auth/data/auth_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase_flutter/supabase_flutter.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i3.AuthState> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i3.AuthState>.empty(),
          )
          as _i4.Stream<_i3.AuthState>);

  @override
  _i3.Session? get currentSession =>
      (super.noSuchMethod(Invocation.getter(#currentSession), returnValue: null)
          as _i3.Session?);

  @override
  _i3.User? get currentUser =>
      (super.noSuchMethod(Invocation.getter(#currentUser), returnValue: null)
          as _i3.User?);

  @override
  String? getUserEmail() =>
      (super.noSuchMethod(
            Invocation.method(#getUserEmail, []),
            returnValue: null,
          )
          as String?);

  @override
  String? getUserName() =>
      (super.noSuchMethod(
            Invocation.method(#getUserName, []),
            returnValue: null,
          )
          as String?);

  @override
  _i4.Future<_i3.AuthResponse> signIn({
    required String email,
    required String password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_1(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<void> signInWithGoogle({required String redirectTo}) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, [], {#redirectTo: redirectTo}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i3.AuthResponse> signUp({
    required String email,
    required String name,
    required String password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #name: name,
              #password: password,
            }),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_1(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #name: name,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<_i3.UserResponse> updateUser({
    String? email,
    String? name,
    String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [], {
              #email: email,
              #name: name,
              #password: password,
            }),
            returnValue: _i4.Future<_i3.UserResponse>.value(
              _FakeUserResponse_2(
                this,
                Invocation.method(#updateUser, [], {
                  #email: email,
                  #name: name,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.UserResponse>);
}

/// A class which mocks [AuthState].
///
/// See the documentation for Mockito's code generation for more information.
class _FakeAuthState_0 extends _i1.SmartFake implements _i3.AuthState {
  _FakeAuthState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthResponse].
///
/// See the documentation for Mockito's code generation for more information.
class _FakeAuthResponse_1 extends _i1.SmartFake implements _i3.AuthResponse {
  _FakeAuthResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserResponse].
///
/// See the documentation for Mockito's code generation for more information.
class _FakeUserResponse_2 extends _i1.SmartFake implements _i3.UserResponse {
  _FakeUserResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}
